In [8]:

# importing the Dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file=pd.read_excel('fraudcalling.csv.xlsx',names=['type','text'])



In [9]:
file


type                                               text
0      fraud  hello, i m bank manager of SBI, ur debit card ...
1      fraud  Todays Vodafone numbers ending with 4882 are s...
2     normal               Please don't say like that. Hi hi hi
3     normal                                         Thank you!
4     normal  Oh that was a forwarded message. I thought you...
...      ...                                                ...
5920   fraud  to get 1000 INR voucher please call on 8898655...
5921   fraud  to get free access of google cloud account hit...
5922   fraud  to get free AWS cloud account hit on given mes...
5923   fraud  to get free access of Microsoft Azure hit on g...
5924   fraud  hello sir, we are from your bank have you fill...

[5925 rows x 2 columns]

In [10]:
X=file[['text']]
y=file[['type']]
y

type
0      fraud
1      fraud
2     normal
3     normal
4     normal
...      ...
5920   fraud
5921   fraud
5922   fraud
5923   fraud
5924   fraud

[5925 rows x 1 columns]

In [11]:
X

text
0     hello, i m bank manager of SBI, ur debit card ...
1     Todays Vodafone numbers ending with 4882 are s...
2                  Please don't say like that. Hi hi hi
3                                            Thank you!
4     Oh that was a forwarded message. I thought you...
...                                                 ...
5920  to get 1000 INR voucher please call on 8898655...
5921  to get free access of google cloud account hit...
5922  to get free AWS cloud account hit on given mes...
5923  to get free access of Microsoft Azure hit on g...
5924  hello sir, we are from your bank have you fill...

[5925 rows x 1 columns]

In [12]:
#Data cleaning and preprocessing
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(X)):
    review = re.sub('[^a-zA-Z]', ' ',X['text'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

corpus


['hello bank manag sbi ur debit card expir would u want issu new card',
 'today vodafon number end select receiv award number match call receiv award',
 'pleas say like hi hi hi',
 'thank',
 'oh forward messag thought send',
 'got seventeen pound seven hundr ml hope ok',
 'funni',
 'sweetheart hope kind day one load reason smile biola',
 'login date time dad fetch home',
 'shower babi',
 'askd u question hour answer',
 'well definit need restock thanksgiv let know',
 'said kiss kiss sound effect gorgeou man kind person need smile brighten day',
 'probabl gonna swing wee bit',
 'ya nice readi thursday',
 'allo brave buse taken train triumph mean b ham jolli good rest week',
 'watch cartoon listen music amp eve go templ amp church',
 'mind ask happen say uncomfort',
 'problem send email',
 'cash prize claim call',
 'that cool sometim slow gentl sometim rough hard',
 'gonna say sorri would normal start panic time sorri see tuesday',
 'hello sir jio custom care hour sim close u want activ'

In [13]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
print(X)

y=pd.get_dummies(file['type'])
y=y.iloc[:,1].values
y

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [16]:
from sklearn.model_selection import train_test_split
X_t, X_test, y_t, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)
X_train, X_val, y_train, y_val = train_test_split(X_t, y_t, test_size = 0.3, random_state = 1)

In [17]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
fraud_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=fraud_detect_model.predict(X_test)

In [18]:
y_pred


array([1, 1, 0, ..., 1, 1, 1], dtype=uint8)

In [19]:
y_test

array([1, 1, 0, ..., 1, 1, 1], dtype=uint8)

In [20]:
import matplotlib.pyplot as plt

In [21]:
y_pred[789]

1

In [22]:
y_test[789]

1

In [23]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(y_pred,y_test))

[[ 119   20]
 [   9 1037]]


In [24]:

from sklearn.metrics import classification_report

print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.93      0.86      0.89       139
           1       0.98      0.99      0.99      1046

    accuracy                           0.98      1185
   macro avg       0.96      0.92      0.94      1185
weighted avg       0.98      0.98      0.98      1185



In [33]:
s=input()
r=[]
p=re.sub('[^a-zA-Z]', ' ',s)
p = p.lower()
p = p.split()
p = [ps.stem(word) for word in p if not word in stopwords.words('english')]
p = ' '.join(p)

r.append(p)

z=cv.transform(r).toarray()
#y=cv.transform(z).toarray()
print(z)
#y_pred_2=fraud_detect_model.predict(z)


hello how are you
[[0 0 0 ... 0 0 0]]


In [34]:
y_pred_2=fraud_detect_model.predict(z)


In [35]:
y_pred_2

array([1], dtype=uint8)

In [36]:
if y_pred_2==[0]:
    print('fraud')
else:
    print('normal')

normal
